### ISSUE TITLE
Runtime Speeds

### ISSUE THREAD

**Issue by vjsrinivas** [Karel911/TRACER#10]
Hi, thanks for putting out an interesting paper and the code. I was testing it with the various pretrained weights on DUT-TE, and I'm getting an end-to-end speed of ~11 FPS on an RTX 2070 Super. Is that an expected speed?

**Comment by Karel911** [comment]
Hi,
Thank you for your interest in our research.
Please check the batch size of 32 and exclude the lines related with measures.
The measuring costs a few minutes so that TRACER shows lower FPS than the original ones.

**Comment by vjsrinivas** [comment]
Hi,
The speeds listed was with batchsize of 1. I commented out the measures lines (the references to `AvgMeter` and the Eval_tool's `cal_total_metrics` and saving the output). Is there anything to comment out? I'm getting 15-16 FPS now.

**Comment by Karel911** [comment]
I tested TE2 under the AMD-RYZEN R9 5900X CPU and single RTX 3090 GPU with batch size of 32.
I obtained the same FPS results listed in our paper.
The FPS inevitably depends on the hardware so that it results in the FPS discrepancy.
Please set the batch size of 32 (as you can) and re-check the FPS.

Thanks,
