### ISSUE TITLE
Testing on test images without mask

### ISSUE THREAD

**Issue by rKrishna97** [Karel911/TRACER#11]
I have few test images without mask. I just want to pass it to the model and get the output. How can I do it?

**Comment by Karel911** [comment]
Hi,
I think you mean you want to get the mask without measuring phase (because the measuring requires a GT of test image).
If what I understand is right, exclude the codes related with evaluation (e.g., line 269) in  `trainer.py` and run `main.py` with test mode (i.e., `python main.py test --save_map True`).

**Comment by rKrishna97** [comment]
Thank you very much :) and Thanks for sharing paper and code
